version: '2.4'

services:
  optimize:
    image: registry.camunda.cloud/optimize-ee/optimize:3.2.0
    container_name: optimize
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
      - OPTIMIZE_CAMUNDABPM_REST_URL=http://cambpm:8080/engine-rest
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
      - OPTIMIZE_CAMUNDA_BPM_EVENT_IMPORT_ENABLED=true
      - OPTIMIZE_EVENT_BASED_PROCESSES_IMPORT_ENABLED=true
      - OPTIMIZE_EVENT_BASED_PROCESSES_USER_IDS=[demo]
      - OPTIMIZE_SUPER_USER_IDS=[demo]
      - OPTIMIZE_EVENT_INGESTION_ACCESS_TOKEN=mytoken
      - WAIT_FOR=elasticsearch:9200
    ports:
      - 8090:8090
    restart: always
    mem_limit: 2g
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    restart: always
    mem_limit: 2g
  cambpm:
    image: registry.camunda.cloud/camunda-bpm-platform-ee:7.14.0
    container_name: cambpm
    environment:
      - TZ=Europe/Berlin
      - JAVA_OPTS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
    ports:
      - 8080:8080
    restart: always
    mem_limit: 2g
