version: '2'

services:
  keycloak-proxy:
    build: keycloak-proxy
    ports:
      - "8095:8095"
    networks:
      - keycloak
    cap_add:
      - ALL

  keycloak-auth:
    build: keycloak-auth
    ports:
      - "8080:8080"
    networks:
      - keycloak

  optimize:
    image: registry.camunda.cloud/optimize-ee/optimize:latest
    container_name: optimize
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
      - OPTIMIZE_CAMUNDABPM_REST_URL=http://cambpm:8080/engine-rest
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
    volumes:
      - ./optimize-config/environment-config.yaml:/optimize/environment/environment-config.yaml
      - ./optimize-config/OptimizeLicense.txt:/optimize/environment/OptimizeLicense.txt
      - ../plugins/sso-plugin/target/sso-plugin-jar-with-dependencies.jar:/optimize/plugin/sso.jar
    restart: always
    mem_limit: 2g
    networks:
      - keycloak

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    container_name: elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=1024mb
      - cluster.routing.allocation.disk.watermark.high=512mb
      - cluster.routing.allocation.disk.watermark.flood_stage=256mb
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - action.auto_create_index=false
      - transport.host=0.0.0.0
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - client.transport.sniff=false
    mem_limit: 1g
    networks:
      - keycloak

  cambpm:
    image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:7.14.0
    container_name: cambpm
    networks:
      - keycloak

networks:
  keycloak:
