version: '3'

services:
  sso-proxy:
    container_name: sso-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
    command: --config /oauth2-proxy.cfg
    hostname: sso-proxy
    volumes:
      - "./oauth2-proxy-keycloak.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    networks:
      - keycloak-network
      - optimize
      - oauth2-proxy
    depends_on:
      - optimize
      - keycloak
    ports:
      - 80:80/tcp

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:15.0.1
    hostname: keycloak
    command:
      [
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/realm-config',
        '-Dkeycloak.migration.strategy=IGNORE_EXISTING',
      ]
    volumes:
      - ./keycloak:/realm-config
    networks:
      keycloak-network:
        aliases:
          - keycloak.localtest.me
    ports:
      - 8080:8080/tcp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/realms/master"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

  optimize:
    image: registry.camunda.cloud/optimize-ee/optimize:${OPTIMIZE_VERSION:?Please provide the Optimize version as OPTIMIZE_VERSION environment variable}
    container_name: optimize
    hostname: optimize
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
      - OPTIMIZE_CAMUNDABPM_REST_URL=http://cambpm:8080/engine-rest
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
    volumes:
      - ./optimize-config/environment-config.yaml:/optimize/config/environment-config.yaml
      - ./optimize-config/OptimizeLicense.txt:/optimize/environment/OptimizeLicense.txt
      - ../plugins/sso-plugin/target/sso-plugin-jar-with-dependencies.jar:/optimize/plugin/sso.jar
    restart: always
    mem_limit: 2g
    networks:
      - optimize

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=1024mb
      - cluster.routing.allocation.disk.watermark.high=512mb
      - cluster.routing.allocation.disk.watermark.flood_stage=256mb
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - action.auto_create_index=false
      - transport.host=0.0.0.0
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - client.transport.sniff=false
    mem_limit: 1g
    networks:
      - optimize

  cambpm:
    image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:7.14.0
    container_name: cambpm
    hostname: cambpm
    networks:
      - optimize

networks:
  optimize: {}
  keycloak-network: {}
  oauth2-proxy: {}
