version: '3.2'

services:
  loadbalancer:
    build: ./load-balancer
    links:
      - optimize1
      - optimize2
    ports: 
      - '8080:8080' 

  optimizeimporter:
    build: ./optimize
    volumes: 
      - "./optimize/environment-config-importer.yaml:/opt/camunda-optimize/environment/environment-config.yaml"

  optimize1:
    build: ./optimize
    volumes: 
      - "./optimize/environment-config.yaml:/opt/camunda-optimize/environment/environment-config.yaml"

  optimize2:
    build: ./optimize
    volumes: 
      - "./optimize/environment-config.yaml:/opt/camunda-optimize/environment/environment-config.yaml"

  elasticsearch:
     environment:
       - cluster.routing.allocation.disk.threshold_enabled=false
       - cluster.name=elasticsearch
       - bootstrap.memory_lock=true
       - discovery.type=single-node
       - action.auto_create_index=false
       - transport.host=0.0.0.0
       - http.host=0.0.0.0
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       - client.transport.sniff=false
     image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.0
     ports:
       - "9300:9300"
       - "9200:9200"
     volumes:
       - elasticsearch-data:/usr/share/elasticsearch/data
       - elasticsearch-logs:/usr/share/elasticsearch/logs

  engine:
    image: registry.camunda.cloud/camunda-bpm-platform-ee:7.10.1
    ports:
      - "8088:8080"

volumes:
  elasticsearch-data:
  elasticsearch-logs:
